name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - run: echo "Your markdown files" > public/
      - uses: actions/upload-pages-artifact@v2